import type { Pulse, Team } from "@/lib/types";

export const mockTeams: Team[] = [
  {
    id: "t1",
    name: "Kjarnateymi",
    isActive: true,
    contact: "Anna",
    meetingCadence: "Vikulega",
    notes: "Regluleg staða á miðvikudögum.",
  },
  {
    id: "t2",
    name: "Vöruþróun",
    isActive: true,
    contact: "Bjorn",
    meetingCadence: "Tveggja vikna fresti",
    notes: "",
  },
];

export const mockPulses: Pulse[] = [
  {
    id: "p1",
    title: "Puls 20.04",
    teamId: "t1",
    teamName: "Kjarnateymi",
    createdDate: "2026-04-20",
    meetingDate: "2026-04-20",
    status: "yellow",
    goals: "Skyrari forgangsrodun i teymi.",
    wins: "Samraemt samtal um stödu.",
    blockers: "Óskýr forgangsröðun á tveimur verkefnum.",
    decisionsNeeded: "Samthykkt a eigendaskiptingu.",
    nextSteps: "Skýra forgang fyrir föstudag og loka eigendaskiptingu.",
    submittedBy: "Anna",
  },
  {
    id: "p2",
    title: "Puls 22.04",
    teamId: "t2",
    teamName: "Vöruþróun",
    createdDate: "2026-04-22",
    meetingDate: "2026-04-22",
    status: "green",
    goals: "Halda afram samraemdri framvindu.",
    wins: "Skyr verkefnastada i lok fundar.",
    blockers: "Engar stórar hindranir núna.",
    decisionsNeeded: "",
    nextSteps: "Halda vikulegri stöðutöku og uppfæra sameiginlega stöðumynd.",
    submittedBy: "Bjorn",
  },
  {
    id: "p3",
    title: "Puls 23.04",
    teamId: "t1",
    teamName: "Kjarnateymi",
    createdDate: "2026-04-23",
    meetingDate: "2026-04-23",
    status: "red",
    goals: "Loka tveimur forgangsatriðum i vikunni.",
    wins: "Skyr mynd af hindrunum komin fram.",
    blockers: "Afhaedni vid ytra teymi hefur tafid framvindu.",
    decisionsNeeded: "Akvordun um forgongsbreytingu i sprinti.",
    nextSteps: "Fá akvordun i dag og uppfaera plan.",
    submittedBy: "Anna",
  },
];
